<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-T7PI7EN2" failures="1" tests="3" name="ForgetTest" time="22.969" errors="0" timestamp="2024-09-02T08:17:50 IST">
  <testcase classname="testcases.Login" name="chkuserid" time="1.103"/>
  <testcase classname="testcases.Login" name="chkpassword" time="15.126">
    <failure type="java.lang.AssertionError" message="error coming when password is valid..">
      <![CDATA[java.lang.AssertionError: error coming when password is valid..
at testcases.Login.chkpassword(Login.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- chkpassword -->
  <testcase classname="testcases.ForgetTest" name="forget" time="1.161"/>
  <testcase classname="core.Page" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="core.Page" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
</testsuite> <!-- ForgetTest -->
